-- Feature-run delivery reconcile (fix: Feature history stuck at `converging`).
--
-- A single-issue feature run hands its opened PR to the convergence loop and then
-- ENDS with `feature_runs.status = 'converging'` (terminal for the run's own
-- process). The PR's live outcome (merged / converged / abandoned) thereafter
-- lives only on the `pull_requests` row keyed by `pr_key`, so the Feature history
-- grid — which reads `feature_runs` — showed `converging` forever even after the
-- PR merged. The epic side already solves the identical gap for `plans` via
-- `pollDelivery` → `plans.delivery` (issue #171); this brings the same reconcile
-- to `feature_runs`.
--
-- `delivery_label` is the human rollup detail projected onto the row by
-- `pollFeatureDelivery` (e.g. "merged", "converged (not merged)", "PR abandoned",
-- or an in-flight sub-state like "waiting_review"). NULL until there is a signal
-- (no `pr_key`, or the run never reached `converging`). The reconciled terminal
-- outcome is written to `status` itself (converging → merged | converged |
-- abandoned) so the existing Status column becomes accurate.
ALTER TABLE feature_runs ADD COLUMN delivery_label TEXT;
