-- ADR 0006 slice S2 (#589) — backfill the `delivery_units` aggregate (088) from the existing rows of
-- the four legacy tables, using the SAME projection the sync triggers (089) apply going forward. Idempotent
-- (`INSERT OR IGNORE` on the `unit_id` PK) so re-running the migration set — or upgrading an install
-- whose triggers already mirrored some rows — never double-inserts. Runs AFTER the triggers so a fresh
-- install with seeded legacy rows is fully covered either way (triggers fire on live writes; this seeds
-- pre-existing rows). The runner wraps each file in its own transaction — no BEGIN/COMMIT here.

INSERT OR IGNORE INTO delivery_units (unit_id, kind, legacy_key, legacy_id, parent_unit_id, node_index, delivery_status, dispatch_status, repo, issue_number, issue_url, title, base_branch, status, process_key, pr_key, converge, auto_merge, outcome, delivery_label, acknowledged_at, stage, stage_state, stage_skipped, attention, list_bucket, created_at, updated_at)
  SELECT 'feature:' || feature_runs.feature_key AS unit_id,
         'feature' AS kind,
         feature_runs.feature_key AS legacy_key,
         NULL AS legacy_id,
         NULL AS parent_unit_id,
         NULL AS node_index,
         CASE WHEN feature_runs.status = 'running' THEN 'running' WHEN feature_runs.status = 'escalated' THEN 'escalated' WHEN feature_runs.status = 'opened' THEN 'opened' WHEN feature_runs.status = 'converging' THEN 'converging' WHEN feature_runs.status = 'awaiting_operator' THEN 'awaiting_operator' WHEN feature_runs.status = 'merged' THEN 'merged' WHEN feature_runs.status = 'converged' THEN 'converged' WHEN feature_runs.status = 'blocked' THEN 'blocked' WHEN feature_runs.status = 'skipped' THEN 'skipped' WHEN feature_runs.status = 'failed' THEN 'failed' WHEN feature_runs.status = 'abandoned' THEN 'abandoned' ELSE NULL END AS delivery_status,
         CASE WHEN feature_runs.status IN ('opened', 'converging', 'merged', 'converged', 'blocked', 'skipped', 'failed', 'abandoned') THEN 'settled' WHEN feature_runs.status IN ('running', 'escalated', 'awaiting_operator') THEN 'dispatched' ELSE NULL END AS dispatch_status,
         feature_runs.repo AS repo,
         feature_runs.issue_number AS issue_number,
         feature_runs.issue_url AS issue_url,
         feature_runs.title AS title,
         feature_runs.base_branch AS base_branch,
         feature_runs.status AS status,
         feature_runs.process_key AS process_key,
         feature_runs.pr_key AS pr_key,
         feature_runs.converge AS converge,
         feature_runs.auto_merge AS auto_merge,
         feature_runs.outcome AS outcome,
         feature_runs.delivery_label AS delivery_label,
         feature_runs.acknowledged_at AS acknowledged_at,
         feature_runs.stage AS stage,
         feature_runs.stage_state AS stage_state,
         feature_runs.stage_skipped AS stage_skipped,
         feature_runs.attention AS attention,
         feature_runs.list_bucket AS list_bucket,
         feature_runs.created_at AS created_at,
         feature_runs.updated_at AS updated_at
  FROM feature_runs;

INSERT OR IGNORE INTO delivery_units (unit_id, kind, legacy_key, legacy_id, parent_unit_id, node_index, delivery_status, dispatch_status, repo, issue_number, issue_url, title, status, task_count, process_key, outcome, gate_wave, blackboard_token, retro_started_at, base_branch, epic_phase, promotion_pr, promotion_state, acknowledged_at, list_bucket, ack_open, wait_gate, wait_gate_label, bound_artifacts, created_at, updated_at)
  SELECT 'epic:' || plans.plan_key AS unit_id,
         'epic' AS kind,
         plans.plan_key AS legacy_key,
         NULL AS legacy_id,
         NULL AS parent_unit_id,
         NULL AS node_index,
         CASE WHEN plans.status = 'planning' THEN 'requested' WHEN plans.status = 'dispatched' THEN 'running' WHEN plans.status = 'done' THEN 'done' WHEN plans.status = 'failed' THEN 'failed' WHEN plans.status = 'abandoned' THEN 'abandoned' ELSE NULL END AS delivery_status,
         CASE WHEN plans.status IN ('planning') THEN 'pending' WHEN plans.status IN ('done', 'failed', 'abandoned') THEN 'settled' WHEN plans.status IN ('dispatched') THEN 'dispatched' ELSE NULL END AS dispatch_status,
         plans.repo AS repo,
         plans.issue_number AS issue_number,
         plans.issue_url AS issue_url,
         plans.title AS title,
         plans.status AS status,
         plans.task_count AS task_count,
         plans.process_key AS process_key,
         plans.outcome AS outcome,
         plans.gate_wave AS gate_wave,
         plans.blackboard_token AS blackboard_token,
         plans.retro_started_at AS retro_started_at,
         plans.base_branch AS base_branch,
         plans.epic_phase AS epic_phase,
         plans.promotion_pr AS promotion_pr,
         plans.promotion_state AS promotion_state,
         plans.acknowledged_at AS acknowledged_at,
         plans.list_bucket AS list_bucket,
         plans.ack_open AS ack_open,
         plans.wait_gate AS wait_gate,
         plans.wait_gate_label AS wait_gate_label,
         plans.bound_artifacts AS bound_artifacts,
         plans.created_at AS created_at,
         plans.updated_at AS updated_at
  FROM plans;

INSERT OR IGNORE INTO delivery_units (unit_id, kind, legacy_key, legacy_id, parent_unit_id, node_index, delivery_status, dispatch_status, title, prompt, status, pr_key, summary, wave, open_question, answer, draft_pr_key, corr_key, created_at, updated_at, task_id)
  SELECT 'plan-task:' || plan_tasks.plan_key || '#' || plan_tasks.task_index AS unit_id,
         'plan-task' AS kind,
         plan_tasks.plan_key AS legacy_key,
         plan_tasks.id AS legacy_id,
         'epic:' || plan_tasks.plan_key AS parent_unit_id,
         plan_tasks.task_index AS node_index,
         CASE WHEN plan_tasks.status = 'pending' THEN 'requested' WHEN plan_tasks.status = 'opened' THEN 'opened' WHEN plan_tasks.status = 'blocked' THEN 'blocked' WHEN plan_tasks.status = 'skipped' THEN 'skipped' WHEN plan_tasks.status = 'escalated' THEN 'escalated' WHEN plan_tasks.status = 'waiting-for-lane' THEN 'waiting' WHEN plan_tasks.status = 'abandoned' THEN 'abandoned' ELSE NULL END AS delivery_status,
         CASE WHEN plan_tasks.status IN ('pending') THEN 'pending' WHEN plan_tasks.status IN ('opened', 'blocked', 'skipped', 'abandoned') THEN 'settled' WHEN plan_tasks.status IN ('escalated', 'waiting-for-lane') THEN 'dispatched' ELSE NULL END AS dispatch_status,
         plan_tasks.title AS title,
         plan_tasks.prompt AS prompt,
         plan_tasks.status AS status,
         plan_tasks.pr_key AS pr_key,
         plan_tasks.summary AS summary,
         plan_tasks.wave AS wave,
         plan_tasks.open_question AS open_question,
         plan_tasks.answer AS answer,
         plan_tasks.draft_pr_key AS draft_pr_key,
         plan_tasks.corr_key AS corr_key,
         plan_tasks.created_at AS created_at,
         plan_tasks.updated_at AS updated_at,
         plan_tasks.task_id AS task_id
  FROM plan_tasks;

INSERT OR IGNORE INTO delivery_units (unit_id, kind, legacy_key, legacy_id, parent_unit_id, node_index, delivery_status, dispatch_status, process_key, process_definition_id, digest, status, side_effecting, node_count, human_node_count, side_effect_count, title, phase, phase_node_id, human_labels, created_at, updated_at)
  SELECT 'delivery-graph:' || delivery_graph_runs.run_key AS unit_id,
         'delivery-graph' AS kind,
         delivery_graph_runs.run_key AS legacy_key,
         NULL AS legacy_id,
         NULL AS parent_unit_id,
         NULL AS node_index,
         CASE WHEN delivery_graph_runs.status = 'awaiting-approval' THEN 'requested' WHEN delivery_graph_runs.status = 'running' THEN 'running' WHEN delivery_graph_runs.status = 'done' THEN 'done' WHEN delivery_graph_runs.status = 'failed' THEN 'failed' WHEN delivery_graph_runs.status = 'abandoned' THEN 'abandoned' ELSE NULL END AS delivery_status,
         CASE WHEN delivery_graph_runs.status IN ('awaiting-approval') THEN 'pending' WHEN delivery_graph_runs.status IN ('done', 'failed', 'abandoned') THEN 'settled' WHEN delivery_graph_runs.status IN ('running') THEN 'dispatched' ELSE NULL END AS dispatch_status,
         delivery_graph_runs.process_key AS process_key,
         delivery_graph_runs.process_definition_id AS process_definition_id,
         delivery_graph_runs.digest AS digest,
         delivery_graph_runs.status AS status,
         delivery_graph_runs.side_effecting AS side_effecting,
         delivery_graph_runs.node_count AS node_count,
         delivery_graph_runs.human_node_count AS human_node_count,
         delivery_graph_runs.side_effect_count AS side_effect_count,
         delivery_graph_runs.title AS title,
         delivery_graph_runs.phase AS phase,
         delivery_graph_runs.phase_node_id AS phase_node_id,
         delivery_graph_runs.human_labels AS human_labels,
         delivery_graph_runs.created_at AS created_at,
         delivery_graph_runs.updated_at AS updated_at
  FROM delivery_graph_runs;
